Users can now only edit/update/delete posts that they've created them…
Sir-Turtle/blog pull request #21
Opened 2017-08-23 22:00 UTC by Sir-Turtle

…selves.

2017-08-23 22:05 UTC, Sir-Turtle commented
Let me know if you have any recommendations regarding ruby/rails code standards. Now that I think of it, I might create two roles, regular users and admin. Then make admin only able to edit/delete/update posts, while reducing access to regular users to just comments that they own.

2017-08-24 18:19 UTC, faragorn requested changes

2017-08-24 18:19 UTC, faragorn commented on app/controllers/posts_controller.rb
> +		if is_current_user_owner(@post)
Looks like you need to introduce policies here, instead of this `if` block, take a look at this gem: https://github.com/elabs/pundit/

2017-08-28 02:02 UTC, Sir-Turtle commented on app/controllers/posts_controller.rb
> +		authorize @post
I'm getting this error here and need to investigate why:
undefined method `authorize' for #<PostsController:0x007ffd26cef510

2017-08-28 03:15 UTC, Sir-Turtle commented on app/controllers/posts_controller.rb
> +		authorize @post
Resolved this issue, needed to "include Pundit" in PostsController. That step wasn't detailed in the pundit gem README, but realized after thanks to stackoverflow :)

2017-08-29 14:21 UTC, faragorn approved these changes
Approved, but some comments needs to be addressed

2017-08-29 14:21 UTC, faragorn commented on test/policies/post_policy_test.rb
> +require 'test_helper'
This tests don't do anything, you can remove it

2017-08-29 14:21 UTC, faragorn commented on app/policies/post_policy.rb
> +		post.user_id == current_user.id
you can do `edit?` instead of duplicating code

2017-08-30 01:36 UTC, merged